remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: AlphaSteph
description: I write about my research on quantitative approaches to trading, and hopefully strategies that can be considered or implemented as a retail trader.
author: Stephanie Liew
