remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
title: Steph's Quant and Trading Research Journal
description: Just a journal where I post my projects on quant and trading research, which includes pure thoughts and perhaps strategies.
author: Stephanie Liew
